### ISSUE TITLE
Example code is missing data analysis

### ISSUE THREAD

**Issue by Pchatain** [malteranalytics/malteranalytics.github.io#4]
Hey, just coming from your article here: https://malteranalytics.github.io/mlb-openpose/ 

I was wondering if I'm looking in the right spot. I clicked on this link and it took me to a single page: [here](https://github.com/malteranalytics/malteranalytics.github.io/blob/master/research/OpenPose.ipynb) 

Are there other files where the data is analyzed through OpenPose?

**Comment by danmalter** [comment]
Hi @Pchatain, the data I used is proprietary, but you can use the code in that link as an example to run against a video file of your choice.

Danny
